### ISSUE TITLE
java.lang.NullPointerException in PyCharm 2022.1

### ISSUE THREAD

**Issue by CodeMouse92** [swdotcom/intellij-codetime#23]
An exception is occurring in the Code Time extension on JetBrains, in particular PyCharm 2022.1 Professional. The plugin was working until the JetBrains Toolbox updated to the most recent build of PyCharm a couple days ago. The plugin is also reporting being up to date. No other problems are occurring, outside of the Code Time plugin.

Here's the IDE version info.

> Build #PY-221.5080.212, built on April 12, 2022
> Runtime version: 11.0.14.1+1-b2043.25 amd64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

Here's the stack trace, which shows up on the IDE launch and any time I try to use any Code Time feature.

```
java.lang.NullPointerException
	at swdc.java.ops.manager.SlackManager.getSlackWorkspaces(SlackManager.java:43)
	at com.softwareco.intellij.plugin.tree.TreeHelper.buildSlackWorkspacesNode(TreeHelper.java:278)
	at com.softwareco.intellij.plugin.tree.TreeHelper.buildMenuNodes(TreeHelper.java:141)
	at com.softwareco.intellij.plugin.tree.CodeTimeToolWindow.makeCodetimeTreeModel(CodeTimeToolWindow.java:123)
	at com.softwareco.intellij.plugin.tree.CodeTimeToolWindow.buildCodeTimeTreeView(CodeTimeToolWindow.java:97)
	at com.softwareco.intellij.plugin.tree.CodeTimeToolWindow.init(CodeTimeToolWindow.java:75)
	at com.softwareco.intellij.plugin.tree.CodeTimeToolWindow.<init>(CodeTimeToolWindow.java:38)
	at com.softwareco.intellij.plugin.tree.CodeTimeToolWindowFactory.createToolWindowContent(CodeTimeToolWindowFactory.java:18)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:528)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:507)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:921)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:861)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl$default(ToolWindowManagerImpl.kt:850)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindow(ToolWindowManagerImpl.kt:749)
	at com.jetbrains.rdserver.toolWindow.BackendServerToolWindowManager.showToolWindow(BackendServerToolWindowManager.kt:181)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.show(ToolWindowImpl.kt:264)
	at com.softwareco.intellij.plugin.tree.CodeTimeToolWindowFactory.openToolWindow(CodeTimeToolWindowFactory.java:29)
	at com.softwareco.intellij.plugin.SoftwareCoSessionManager.statusBarClickHandler(SoftwareCoSessionManager.java:76)
	at com.softwareco.intellij.plugin.SoftwareCoStatusBarKpmIconWidget$1.consume(SoftwareCoStatusBarKpmIconWidget.java:33)
	at com.softwareco.intellij.plugin.SoftwareCoStatusBarKpmIconWidget$1.consume(SoftwareCoStatusBarKpmIconWidget.java:30)
	at com.intellij.openapi.wm.impl.status.widget.StatusBarWidgetWrapper$StatusBarWidgetClickListener.onClick(StatusBarWidgetWrapper.java:173)
	at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:59)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6654)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6419)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2793)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:743)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:119)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by CodeMouse92** [comment]
It appears to be resolved. Thanks!
